- apps/common-app/src/App.tsx
- apps/common-app/src/components/Select.tsx
- apps/common-app/src/examples/DrumMachine/DrumMachine.tsx
- apps/common-app/src/examples/DrumMachine/usePlayer.tsx
- apps/fabric-example/ios/Podfile.lock
Closes #189 
- Removes `playTheNote` out of `usePlayer hook, in favour of `setup` method provided by the parent component.
> [#189] Move playNote function outside of usePlayer hook scope

- packages/react-native-audio-api/src/index.native.ts
- packages/react-native-audio-api/src/index.ts
Closes #193 
- Adds web compatible wrapper classes which match with our implementation of web audio api
> feat: simple web audio api wrappers

- .github/workflows/publish-docs.yml
> Publish docs to github pages workflow

- README.md
- packages/audiodocs/README.md
- packages/audiodocs/docs/fundamentals/getting-started.mdx
- packages/audiodocs/docs/fundamentals/introduction.mdx
- packages/audiodocs/prettier.config.js
- packages/audiodocs/src/components/LandingPage/OscillatorSquare.module.css
- packages/audiodocs/src/components/LandingPage/OscillatorSquare.tsx
- packages/react-native-audio-api/package.json
Closes #260 
- adds introduction page with some example of the api usage
> Docs: intro page

- apps/common-app/src/components/Container.tsx
- apps/common-app/src/examples/AudioVisualizer/AudioVisualizer.tsx
- apps/common-app/src/examples/AudioVisualizer/Charts.tsx
- apps/common-app/src/examples/DrumMachine/Grid.tsx
> feat: some changes to the audio visualizer example

- packages/audiodocs/docs/guides/noise_generation.mdx
- packages/audiodocs/docusaurus.config.js
- packages/audiodocs/package.json
- packages/audiodocs/src/components/LandingPage/OscillatorSquare.module.css
- packages/audiodocs/src/examples/NoiseGeneration/BrownianNoiseComponent.tsx
- packages/audiodocs/src/examples/NoiseGeneration/BrownianNoiseSource.tsx
- packages/audiodocs/src/examples/NoiseGeneration/PinkNoiseComponent.tsx
- packages/audiodocs/src/examples/NoiseGeneration/PinkNoiseSource.tsx
- packages/audiodocs/src/examples/NoiseGeneration/WhiteNoiseComponent.tsx
- packages/audiodocs/src/examples/NoiseGeneration/WhiteNoiseSource.tsx
- packages/audiodocs/yarn.lock
Closes #
- adds noise generation guide
> Docs: noise guide

- packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.cpp
Closes #
-  Added support for playing different AudioBuffer sample rates
> feat: added support for playing different AudioBuffer sample rates

- apps/fabric-example/android/gradle.properties
- packages/react-native-audio-api/android/build.gradle
Closes #284
- Added support for x86_64
> feat: added support for x86_64

- apps/fabric-example/android/gradle.properties
- packages/react-native-audio-api/android/build.gradle
Closes #
- Added support for x86
> feat: added support for x86

- packages/react-native-audio-api/common/cpp/core/AudioContext.cpp
- packages/react-native-audio-api/common/cpp/core/AudioNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioNode.h
- packages/react-native-audio-api/common/cpp/core/AudioNodeManager.cpp
- packages/react-native-audio-api/common/cpp/core/AudioNodeManager.h
- packages/react-native-audio-api/common/cpp/core/AudioScheduledSourceNode.cpp
- packages/react-native-audio-api/common/cpp/core/BaseAudioContext.cpp
Closes #288 
Closes #285
- Fix preparing nodes for deconstruction process
- Refactored management of nodes life cycle
> Fix/initializing context/deconstruction bug

- packages/react-native-audio-api/common/cpp/HostObjects/BaseAudioContextHostObject.h
- packages/react-native-audio-api/common/cpp/jsi/JsiPromise.cpp
- packages/react-native-audio-api/common/cpp/jsi/JsiPromise.h
Closes #286 
- Fixed `JsiPromise`
> fix: fixed jsi promise

- packages/audiodocs/docs/other/web-audio-api-coverage.mdx
- packages/react-native-audio-api/android/src/main/cpp/core/AudioPlayer.cpp
- packages/react-native-audio-api/common/cpp/core/AnalyserNode.cpp
- packages/react-native-audio-api/common/cpp/core/AnalyserNode.h
- packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioBus.cpp
- packages/react-native-audio-api/common/cpp/core/AudioBus.h
- packages/react-native-audio-api/common/cpp/core/AudioDestinationNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioNode.h
- packages/react-native-audio-api/common/cpp/core/OscillatorNode.cpp
- packages/react-native-audio-api/common/cpp/core/StereoPannerNode.cpp
- packages/react-native-audio-api/ios/core/IOSAudioPlayer.mm
Closes #248 
- Refactored inputs mixing logic. Currently we are using all mixing-related params: `channelCount`, `channelCountMode` and `channelInterpretation`. 
- Checked and updated all mixing sensitive/related places in the core
> Refactor/audio node/mixing logic

- .github/workflows/publish-docs.yml
> Use separate branch for docs publication

- packages/react-native-audio-api/android/src/main/cpp/core/AudioPlayer.cpp
- packages/react-native-audio-api/android/src/main/cpp/core/AudioPlayer.h
- packages/react-native-audio-api/common/cpp/core/AudioContext.cpp
- packages/react-native-audio-api/common/cpp/core/AudioContext.h
- packages/react-native-audio-api/common/cpp/core/AudioDestinationNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioDestinationNode.h
- packages/react-native-audio-api/common/cpp/core/AudioNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioNode.h
- packages/react-native-audio-api/ios/core/IOSAudioPlayer.h
- packages/react-native-audio-api/ios/core/IOSAudioPlayer.mm
Closes #
- Replaced raw pointers to `AudioBus` to shared pointers
> fix: switch from raw pointers to AudioBus to shared_ptr

- packages/react-native-audio-api/android/src/main/cpp/core/AudioDecoder.cpp
- packages/react-native-audio-api/common/cpp/core/AnalyserNode.cpp
- packages/react-native-audio-api/common/cpp/core/AnalyserNode.h
- packages/react-native-audio-api/common/cpp/core/AudioBuffer.cpp
- packages/react-native-audio-api/common/cpp/core/AudioBuffer.h
- packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.h
- packages/react-native-audio-api/common/cpp/core/AudioDecoder.h
- packages/react-native-audio-api/common/cpp/core/AudioDestinationNode.h
- packages/react-native-audio-api/common/cpp/core/AudioNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioNode.h
- packages/react-native-audio-api/common/cpp/core/AudioScheduledSourceNode.cpp
- packages/react-native-audio-api/common/cpp/core/AudioScheduledSourceNode.h
- packages/react-native-audio-api/common/cpp/core/BiquadFilterNode.cpp
- packages/react-native-audio-api/common/cpp/core/BiquadFilterNode.h
- packages/react-native-audio-api/common/cpp/core/GainNode.cpp
- packages/react-native-audio-api/common/cpp/core/GainNode.h
- packages/react-native-audio-api/common/cpp/core/OscillatorNode.cpp
- packages/react-native-audio-api/common/cpp/core/OscillatorNode.h
- packages/react-native-audio-api/common/cpp/core/StereoPannerNode.cpp
- packages/react-native-audio-api/common/cpp/core/StereoPannerNode.h
- packages/react-native-audio-api/ios/core/AudioDecoder.mm
Closes #
-  Replaced all `AudioBus` raw pointer to shared pointers
> refactor: replaced all AudioBus raw pointer to shared pointers

- packages/react-native-audio-api/android/src/main/cpp/core/AudioPlayer.cpp
- packages/react-native-audio-api/android/src/main/cpp/core/AudioPlayer.h
- packages/react-native-audio-api/common/cpp/HostObjects/AudioContextHostObject.h
- packages/react-native-audio-api/common/cpp/core/AudioContext.cpp
- packages/react-native-audio-api/common/cpp/core/AudioContext.h
- packages/react-native-audio-api/ios/core/AudioPlayer.h
- packages/react-native-audio-api/ios/core/AudioPlayer.m
- packages/react-native-audio-api/ios/core/IOSAudioPlayer.h
- packages/react-native-audio-api/ios/core/IOSAudioPlayer.mm
- packages/react-native-audio-api/src/core/AudioContext.ts
- packages/react-native-audio-api/src/interfaces.ts
- packages/react-native-audio-api/src/web-core/AudioContext.tsx
…e configuration change events
Closes #
- adds pause and suspense methods of audio context
- reconnect audio engine on engine configuration changes
- slightly refactored AVAudioSession management
> Pause and Suspense, handle audio engine conf change

- .github/release.yml
Closes #
- Added template for release notes
> chore: added release.yml

- packages/audiodocs/package.json
- packages/react-native-audio-api/package.json
> chore: released 0.5.1

- packages/audiodocs/src/examples/LetsMakeSomeNoise/Component.tsx
- packages/audiodocs/src/examples/NoiseGeneration/BrownianNoiseComponent.tsx
- packages/audiodocs/src/examples/NoiseGeneration/PinkNoiseComponent.tsx
- packages/audiodocs/src/examples/NoiseGeneration/WhiteNoiseComponent.tsx
- packages/audiodocs/src/examples/SeeYourSound/BaseComponent.tsx
- packages/audiodocs/src/examples/SeeYourSound/FrequencyDomainComponent.tsx
- packages/audiodocs/src/examples/SeeYourSound/TimeDomainComponent.tsx
- packages/audiodocs/src/examples/SimplePiano/EnvelopesComponent.tsx
- packages/audiodocs/src/examples/SimplePiano/FinalComponent.tsx
- packages/audiodocs/src/examples/SimplePiano/ItHangsComponent.tsx
- packages/audiodocs/src/examples/SimplePiano/PressOutComponent.tsx
- packages/audiodocs/yarn.lock
Closes #
- Added missing async-await to web components in docs
> fix: added missing async-await RNAA-22

- apps/fabric-example/ios/Podfile.lock
- packages/audiodocs/package.json
- packages/react-native-audio-api/common/cpp/audioapi/core/AudioNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
> chore: release-0.5.2

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/package.json
> chore: released 0.5.3

- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.h
> fix: better buffer locking and assertions

- apps/common-app/src/examples/DrumMachine/constants.ts
- apps/fabric-example/ios/Podfile.lock
- packages/audiodocs/package.json
- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIPackage.kt
- packages/react-native-audio-api/package.json
> chore: released 0.5.4

- apps/fabric-example/ios/Podfile.lock
- packages/audiodocs/package.json
- packages/react-native-audio-api/package.json
> chore: released 0.5.5

- apps/common-app/src/examples/AudioFile/AudioFile.tsx
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
Closes #
- Fixed delayed start bug
- Added start and stoping in the same render quantum
> fix: delayed start

- apps/fabric-example/ios/Podfile.lock
- packages/audiodocs/package.json
- packages/react-native-audio-api/package.json
> chore: released 0.5.6

- packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
Closes #
- Fixed event name typo
> fix: fixed event name typo

- apps/fabric-example/ios/FabricExample.xcodeproj/project.pbxproj
- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/package.json
> chore: released 0.6.0-rc.1

- README.md
> Cleanup readme and add roadmap

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
- packages/react-native-audio-api/package.json
> Release/0.6.0 rc.2

- apps/common-app/src/examples/Record/Record.tsx
- packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.h
- packages/react-native-audio-api/ios/audioapi/ios/core/IOSAudioRecorder.mm
Part of RNAA-72
- Added custom buffer length in iOS `AudioRecorder`
> feat: added custom buffer length on iOS

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/package.json
> chore: released 0.6.0-rc.4

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
- packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
- packages/react-native-audio-api/package.json
> Release/0.6.0 rc.5

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt
- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/VolumeChangeListener.kt
- packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.cpp
- packages/react-native-audio-api/package.json
> chore: released 0.6.0 and fixed merge changes

- packages/audiodocs/docs/fundamentals/getting-started.mdx
Closes #445 
- Update's installation docs to include metro config
> update installation docs to include metro config

- packages/audiodocs/docs/core/base-audio-context.mdx
- packages/audiodocs/docs/effects/stereo-panner-node.mdx
- added docs for stereo panner node
> docs: stereo panner node

- packages/audiodocs/docs/sources/oscillator-node.mdx
fixes #455 comment
- fix of wrong description in docs regarding oscillator node
> fix: number of channelCount

- .github/workflows/publish-docs.yml
- packages/audiodocs/docusaurus.config.js
- packages/audiodocs/src/theme/Navbar/index.jsx
Closes RNAA-25
- added search bar into the docs
- added job for recalculating index when new changes are introduced
> docs: added search bar into the documentation

- packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
- packages/react-native-audio-api/src/events/types.ts
Closes RNAA-121
- changed to more sctrict typing, by introducing string union in type
> fix: changed type of reason to string union

- packages/react-native-audio-api/android/src/oldarch/NativeAudioAPIModuleSpec.java
> fix: fixed NativeAudioAPIModuleSpec on oldArch

- packages/react-native-audio-api/src/web-core/AudioBufferSourceNode.tsx
- packages/react-native-audio-api/src/web-core/AudioNode.tsx
- packages/react-native-audio-api/src/web-core/AudioParam.tsx
- packages/react-native-audio-api/src/web-core/BiquadFilterNode.tsx
- packages/react-native-audio-api/src/web-core/GainNode.tsx
- packages/react-native-audio-api/src/web-core/OscillatorNode.tsx
- packages/react-native-audio-api/src/web-core/StereoPannerNode.tsx
> fix: possibility of connecting node to param on web

- packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferQueueSourceNodeHostObject.h
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.h
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
- packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
- packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
- packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
- packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
- packages/react-native-audio-api/src/events/types.ts
- packages/react-native-audio-api/src/interfaces.ts
Closes #
- Implemented pause method in `AudioBufferQueueSourceNode`
- Refactored `onPositionChangeEvent`
> Cant wait to do that - PAUSE in RN-Audio-API

- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.h
- packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
- packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
> fix: fixed stop

- apps/common-app/src/examples/AudioFile/AudioFile.tsx
- apps/common-app/src/examples/AudioFile/AudioPlayer.ts
- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/LockScreenManager.kt
- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
- packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/effects/CustomProcessorNode.h
- packages/react-native-audio-api/src/api.ts
- packages/react-native-audio-api/src/core/BaseAudioContext.ts
- packages/react-native-audio-api/src/core/CustomProcessorNode.ts
- packages/react-native-audio-api/src/types.ts
Closes #
-
- Fixed lock screen skip commands on Android above 12
> fix: fixed lock screen skip commands for android above 12

- apps/common-app/src/examples/AudioFile/AudioPlayer.ts
- packages/audiodocs/docs/other/compatibility.mdx
- packages/audiodocs/docs/other/web-audio-api-coverage.mdx
Closes #
- Updated Web Audio API coverage and compatibility table
-
> docs: updated compatibility table and web audio mapi coverage

- packages/audiodocs/docs/other/compatibility.mdx
> docs: updated compatibility table

- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioAPIModule.kt
Promise has to be resolved to use async/await
Closes #
-
-
> fix: resolve setAudioSessionActivity

- .github/workflows/publish-docs.yml
- packages/audiodocs/docusaurus.config.js
- packages/audiodocs/package.json
- packages/audiodocs/patches/@swmansion+t-rex-ui+1.0.0.patch
- packages/audiodocs/yarn.lock
Closes RNAA-159
- i solemnly swear that i am up to no good
- Hax around to show algolia search on "not-landing" landing page
- Remove unnecessary "guides" link from navbar
- run docs publish only on manual trigger
> fix: show algolia search on not landing - landing page

- .github/workflows/npm-audio-package-build.yml
- .github/workflows/npm-publish-nightly.yml
- README.md
Closes RNAA-160
-
- added script that supports both publishing new version of package and also nightly
- updated readme
> chore: workflow script and readme

- .github/workflows/npm-audio-package-build.yml
- .github/workflows/npm-publish-nightly.yml
- .github/workflows/publish-docs.yml
- .github/workflows/tests.yml
- README.md
Closes #
-
- fixed wrong links in readme
- unified workflows naming
> fix: links in readme

- packages/audiodocs/docs/core/base-audio-context.mdx
- packages/audiodocs/docs/sources/audio-buffer.mdx
- packages/audiodocs/docs/sources/audio-scheduled-source-node.mdx
Closes #
-
- Updated docs for `onEnded` and `decodePCMInBase64Data`
> docs: updated docs fro onEnded and extracted decoding method

- packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
- packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
- packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.cpp
- packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiPromise.cpp
- packages/react-native-audio-api/common/cpp/test/CMakeLists.txt
Closes #
-
- refactored cmake file, get rid of unnecessary macros
- bump gtest version
- namespaces and headers for compability with job compilator
> test: refactor tests

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionCallback.kt
- packages/react-native-audio-api/package.json
> fix: fixed package json version

- packages/audiodocs/docs/core/base-audio-context.mdx
Closes RNAA-167 RNAA-172
-
- introduced code examples for all decoding methods
> docs: examples for various decoding

- packages/audiodocs/docs/core/base-audio-context.mdx
- packages/audiodocs/docs/effects/biquad-filter-node.mdx
- packages/audiodocs/docs/effects/stereo-panner-node.mdx
- packages/audiodocs/docs/guides/create-your-own-effect.mdx
- packages/audiodocs/docs/guides/see-your-sound.mdx
- packages/audiodocs/docs/inputs/audio-recorder.mdx
- packages/audiodocs/docs/sources/recorder-adapter-node.mdx
- packages/audiodocs/docs/system/audio-manager.mdx
> fix: docpage links

- packages/audiodocs/docs/fundamentals/getting-started.mdx
- packages/audiodocs/docs/other/audio-api-plugin.mdx
- packages/react-native-audio-api/src/plugin/withAudioAPI.ts
Closes #592 
- `NSMicrophoneUsageDescription` can be specified via config plugin
> feat: added option for microphone usage description to config plugin

- packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferHostObject.h
- packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiHostObject.cpp
- packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiHostObject.h
Closes #
-
- turned off JSI_DEBUG_ALLOCATIONS
> fix: turned off JSI_DEBUG_ALLOCATIONS

- packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
Closes #603
-
- added copying outputnodes map, because disconnecting nodes remove elements from map under the hood
> fix: disconnecting all nodes in manager

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-audio-api/package.json
> chore: release 0.7.1

- apps/common-app/src/examples/Record/Record.tsx
- packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.m
- packages/react-native-audio-api/ios/audioapi/ios/system/AudioEngine.mm
Closes #621, RNAA-96
-
- improved handling native side with input node
- refactored recording example app
> fix: proper recording stopping

- packages/audiodocs/docs/other/compatibility.mdx
Closes #
-
- Updated compatibility table
> docs: small update to compatibility table

- packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
- packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/FFmpegDecoding.cpp
- packages/react-native-audio-api/common/cpp/audioapi/libs/ffmpeg/FFmpegDecoding.h
- packages/react-native-audio-api/ios/audioapi/ios/core/AudioDecoder.mm
Closes #650 
-
- now passing channel number from decoder to decoding pipeline in ffmpeg to always align with desired number of channels
> fix: number of channels

- packages/audiodocs/docs/core/audio-context.mdx
- packages/audiodocs/docs/core/audio-param.mdx
- packages/audiodocs/docs/core/base-audio-context.mdx
- packages/audiodocs/docs/sources/audio-buffer-source-node.mdx
- packages/audiodocs/docs/sources/audio-buffer.mdx
- packages/audiodocs/docs/sources/audio-scheduled-source-node.mdx
- packages/audiodocs/docs/sources/oscillator-node.mdx
- packages/audiodocs/docs/sources/streamer-node.mdx
> docs: improvements

- packages/custom-node-generator/bin/cli.js
- packages/custom-node-generator/package.json
Closes #
-
- in 0.0.4 somehow line about binary was deleted and version 0.0.4 wasn't working with npx
> fix: added bin to package.json

- apps/common-app/src/examples/Record/Record.tsx
> fix: fixed recorder setup
