packages/react-native-audio-api/android/CMakeLists.txt
packages/react-native-audio-api/android/libs/include/fftw3/fftw3.h
packages/react-native-audio-api/common/cpp/utils/android/FFTFrame.cpp

- Switch kfr lib to fftw3 due to license

fix: switch from kfr to fftw3

---

apps/common-app/src/examples/DrumMachine/usePlayer.tsx
packages/react-native-audio-api/android/src/main/cpp/AudioPlayer/AudioPlayer.cpp
packages/react-native-audio-api/android/src/main/cpp/AudioPlayer/AudioPlayer.h
packages/react-native-audio-api/common/cpp/core/AudioContext.cpp
packages/react-native-audio-api/common/cpp/core/AudioDestinationNode.cpp
packages/react-native-audio-api/common/cpp/core/BaseAudioContext.cpp
packages/react-native-audio-api/common/cpp/core/BaseAudioContext.h

Closes #
- Fixes android issues when starting/stopping audio context and player
- Fixes issue with construction and deconstruction of AudioContext and Player

fix: base audio context construction + audio player start stop events

---

packages/react-native-audio-api/common/cpp/core/AudioDestinationNode.cpp
packages/react-native-audio-api/common/cpp/core/BaseAudioContext.cpp
packages/react-native-audio-api/ios/AudioPlayer/AudioPlayer.m

Closes #228 
- Fixes issue with preferredIOSBufferDuration being 0 on real iOS device

fix: correct buffer lengths on real ios devices

---

apps/common-app/src/examples/Piano/PianoNote.tsx
apps/common-app/src/utils/usePlayer.tsx
packages/audiodocs/docs/fundamentals/making-a-piano-keyboard.mdx
packages/audiodocs/src/examples/SimplePiano/EnvelopesComponent.tsx
packages/audiodocs/src/examples/SimplePiano/EnvelopesSource.tsx
packages/audiodocs/src/examples/SimplePiano/FinalComponent.tsx
packages/audiodocs/src/examples/SimplePiano/FinalSource.tsx
packages/react-native-audio-api/common/cpp/core/AudioScheduledSourceNode.cpp

Closes #250 
- Fixes issue with calculation of `nonSilentFramesToProcess` inside AudioScheduledSourceNode, which was causing size_t overflow for `startOffset > 0` resulting in writing outside of buffers causing various crashes
- [Docs and Example] sets minimal piano key sound duration to 5 seconds (sounds more natural ;))
- usePlayer - use the real timestamp of the note to play instead overwriting it with "render quantum" start

Fixes: ASSN, piano minimal sound length, usePlayer timing

---

apps/common-app/src/examples/AudioFile/AudioFile.tsx
apps/common-app/src/examples/AudioVisualizer/AudioVisualizer.tsx
docs/web-audio-coverage.md
packages/react-native-audio-api/common/cpp/HostObjects/AudioBufferSourceNodeHostObject.h
packages/react-native-audio-api/common/cpp/HostObjects/AudioScheduledSourceNodeHostObject.h
packages/react-native-audio-api/common/cpp/core/AudioBuffer.cpp
packages/react-native-audio-api/common/cpp/core/AudioBuffer.h
packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.cpp
packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.h
packages/react-native-audio-api/common/cpp/core/AudioScheduledSourceNode.cpp
packages/react-native-audio-api/common/cpp/core/AudioScheduledSourceNode.h
packages/react-native-audio-api/src/core/AudioBufferSourceNode.ts
packages/react-native-audio-api/src/core/AudioScheduledSourceNode.ts
packages/react-native-audio-api/src/index.ts
packages/react-native-audio-api/src/interfaces.ts

Closes #282
Closes #163 
- Implemented `AudioBufferSourceNode's` `start(when, offset, duration)` method. Currently it is possible to call classic `pause` on buffer playback.

Feat/audio buffer source node/override start method

---

packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.cpp
packages/react-native-audio-api/common/cpp/core/AudioBufferSourceNode.h

Closes #
- Adds Lock mechanism to read/write from buffer in audio buffer source node to avoid reading from incompletely copied buffer, which might lead to nullptrs

fix: add lock mechanism to buffer changes in ABSN

---

packages/react-native-audio-api/common/cpp/audioapi/core/OfflineAudioContext.cpp

Closes #
- Initialize `resutBus_` after `sampleRate_`

fix: fixed resultBus_ initializing, it should happen after sampleRate

---

packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeDestructor.cpp

- `AudioNodeDestructor::thread_` is initialized on initialization list, while its thread captures `this` itself.
I've experienced app crash on iOS, at line `cv_.wait(lock, [this] {`
```cpp
void AudioNodeDestructor::process() {
std::unique_lock<std::mutex> lock(mutex_);
while (!isExiting_) {
cv_.wait(lock, [this] {
return isExiting_ || !nodesForDeconstruction_.empty();
});
if (isExiting_)
break;
if (!isExiting_ && !nodesForDeconstruction_.empty()) {
nodesForDeconstruction_.clear();
}
}
}
```
with error 
```
libc++abi: terminating due to uncaught exception of type std::__1::system_error: condition_variable wait failed: Invalid argument
```
It seems like a thread trying to access some uninitialized value of `this` .
After moving code to initialize thread on its constructor, no more crash …

fix: create thread on constructor, after others are initialized

---

packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h

Closes #357
Closes RNAA-40
- Fixed calling `onended` callback twice

fix: onended callback calling twice

---

packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioNodeManager.h

Closes #400 
Closes RNAA-62
- added checks during destruction in order not to destroy playing source nodes

fix: remove playing nodes from destruction

---

packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm

Closes RNAA-54
- Added hook that allows user track volume value in ios

feat: useSystemVolume hook for ios

---

apps/common-app/src/examples/AudioFile/AudioFile.tsx
packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/AudioManagerModule.kt
packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionEventEmitter.kt
packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/MediaSessionManager.kt
packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/VolumeChangeListener.kt
packages/react-native-audio-api/ios/audioapi/ios/AudioManagerModule.mm
packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.h
packages/react-native-audio-api/ios/audioapi/ios/system/NotificationManager.mm
packages/react-native-audio-api/src/api.ts
packages/react-native-audio-api/src/hooks/useSytemVolume.ts
packages/react-native-audio-api/src/specs/NativeAudioManagerModule.ts
packages/react-native-audio-api/src/system/AudioManager.ts
packages/react-native-audio-api/src/system/types.ts
packages/react-native-audio-api/src/system/useSystemVolume.ts

Closes RNAA-55
- Added hook that allows user track volume value in android

feat: useSystemVolume hook for android

---

packages/react-native-audio-api/common/cpp/audioapi/core/analysis/AnalyserNode.cpp

Closes #
- Added correct offset while copying buffer in `AnalyserNode`

Fix/analyser node/wrong offset while copying

---

packages/audiodocs/docs/guides/lets-make-some-noise.mdx

Fixed some tiny highlighting problems in docs

docs: fix highlighted sections in lets-make-some-noise

---

packages/react-native-audio-api/common/cpp/audioapi/core/sources/OscillatorNode.cpp

Closes RNAA-104
- get rid of a round function that caused oscillator node to always oscillate with integer frequencies (having fractional frequencies can be useful when dealing with LFOs when this parameter can be less than 1Hz)

fix: get rid of round that caused frequency to be always int

---

packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiPromise.cpp

https://github.com/software-mansion/react-native-audio-api/issues/397#issuecomment-2868715608
- Fixed reject wrapper in `JsiPromise`

fix: fixed reject wrapper in jsi promise

---

packages/audiodocs/docs/core/audio-node.mdx

Closes RNAA-112
- added documentation for connecting node to param

docs: add mention about connecting node to param

---

packages/react-native-audio-api/src/core/AudioNode.ts

Closes RNAA-113
- allowed disconnect function to also have an audio param as an argument

fix: added possibility of disconnection between node and param in ts

---

packages/audiodocs/docs/system/audio-manager.mdx
packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.h
packages/react-native-audio-api/ios/audioapi/ios/system/AudioSessionManager.mm
packages/react-native-audio-api/src/specs/NativeAudioAPIModule.ts
packages/react-native-audio-api/src/system/AudioManager.ts
packages/react-native-audio-api/src/system/types.ts

Closes #
- Added support for the allowHapticsAndSystemSoundsDuringRecording option in AudioSessionManager for iOS (iOS 13+).
- Updates types and config on both Objective-C and TypeScript sides.
- Now possible to enable haptic and system sounds while recording audio sessions on iOS.

feat: add haptics support for iOS audio sessions

---

packages/react-native-audio-api/android/src/main/cpp/audioapi/android/core/AudioDecoder.cpp
packages/react-native-audio-api/common/cpp/audioapi/HostObjects/BaseAudioContextHostObject.h
packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/BaseAudioContext.h
packages/react-native-audio-api/common/cpp/audioapi/core/utils/AudioDecoder.h
packages/react-native-audio-api/common/cpp/audioapi/libs/base64/base64.h
packages/react-native-audio-api/ios/audioapi/ios/core/AudioDecoder.mm
packages/react-native-audio-api/src/core/BaseAudioContext.ts
packages/react-native-audio-api/src/interfaces.ts

Closes #
- Implemented new decoding feature. Passing string to `decodeAudioData` allows to decode base64 pcm 16int data

feat: implemented decoding pcm in base64

---

apps/fabric-example/ios/Podfile.lock
packages/react-native-audio-api/package.json

chore: released 0.6.3

---

apps/common-app/src/examples/AudioFile/AudioFile.tsx
packages/react-native-audio-api/android/src/main/cpp/audioapi/android/AudioAPIModule.cpp
packages/react-native-audio-api/android/src/main/java/com/swmansion/audioapi/system/AudioFocusListener.kt

Closes #
-
- Fixed typo in interruption body event on Android
- Fixed type of `shouldResume` on Android

fix: fixed typo

---

packages/react-native-audio-api/android/src/main/cpp/audioapi/android/AudioAPIModule.cpp
packages/react-native-audio-api/common/cpp/audioapi/HostObjects/AudioBufferBaseSourceNodeHostObject.h
packages/react-native-audio-api/common/cpp/audioapi/core/AudioParam.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/inputs/AudioRecorder.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferBaseSourceNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferBaseSourceNode.h
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.h
packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.cpp
packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.h
packages/react-native-audio-api/ios/audioapi/ios/AudioAPIModule.mm
packages/react-native-audio-api/package.json
packages/react-native-audio-api/src/core/AudioBufferBaseSourceNode.ts
packages/react-native-audio-api/src/core/AudioScheduledSourceNode.ts

Closes RNAA-154
- most likely none 🤫 
- adds missing getters for `onPositionChanged` callback and interval prop (eventually someone will try to console log that and will crash ;))
- add / remove event handler methods are now runned inside `invokeAsync` lambda to esnure any modification or reading from the callback map is queueud (and always on the same thread)
- invoke callback is now entirely done in the JS thread (and queue)
- atomic thread id counter!

More gracefull event handling from audio thread

---

packages/react-native-audio-api/common/cpp/audioapi/utils/CircularOverflowableAudioArray.h

Closes #
PR, because react compiles c++ with `-Werror`, which caused this code to fail compilation, because it raised a warning.

fix: hotfixed warning which caused builds to fail

---

packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioPlayer.m
packages/react-native-audio-api/ios/audioapi/ios/core/NativeAudioRecorder.m

audio engine needs to be restarted upon changing anything like attaching detaching nodes.
Works fine
Closes #598 
Closes #596

fix: recorder and audio context issue

---

packages/audiodocs/docs/other/compatibility.mdx
packages/react-native-audio-api/android/build.gradle
packages/react-native-audio-api/android/src/main/cpp/audioapi/CMakeLists.txt

- Dropped support for RN 0.75
-

[blocked] chore: dropped support for RN 0.75

---

packages/audiodocs/docs/sources/streamer-node.mdx
packages/react-native-audio-api/src/core/AudioContext.ts
packages/react-native-audio-api/src/interfaces.ts

Closes #638
-
- changed type of promise from boolean to void in close method of AudioContext
- added mention about streamer node being mobile only in docs

fix: change type to void

---

packages/react-native-audio-api/src/web-core/custom/LoadCustomWasm.ts

-
- Added an optional path prefix to `LoadCustomWasm.ts`, this allows us to properly load `signalsmithStretch` script from our docs

fix: add optional path prefix to LoadCustomWasm

---

packages/audiodocs/src/components/InteractivePlayground/AudioBufferSourceExample/AudioBufferSourceExample.tsx

Closes 
- added correct param initialization when playing the sample in 'AudioBufferSourceExample' so it always starts with correct parameters chosen by the user

Fix: correct param initialization on play in AudioBufferSource interactive playground

---

packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiPromise.cpp
packages/react-native-audio-api/common/cpp/audioapi/jsi/JsiPromise.h

Implemented method that simplifies creating promises that are heavy and should be resolved on separate thread. It also creates a room for adding thread pool in a future.

feat: async promise resolving

---

apps/fabric-example/ios/Podfile.lock
packages/audiodocs/docs/sources/audio-buffer-queue-source-node.mdx
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferQueueSourceNode.cpp
packages/react-native-audio-api/src/core/OscillatorNode.ts
packages/react-native-audio-api/src/events/types.ts

Closes RNAA-223
-
- Added `isLast` property to onEnded event payload in `AudioBufferQueueSourceNode` indicating if it was the last buffer in the queue

Feat/audio buffer queue source node/extened on ended event payload

---

apps/common-app/src/examples/PlaybackSpeed/constants.ts
apps/fabric-example/ios/Podfile.lock
packages/audiodocs/docs/sources/audio-buffer-source-node.mdx
packages/react-native-audio-api/common/cpp/audioapi/HostObjects/sources/AudioBufferSourceNodeHostObject.cpp
packages/react-native-audio-api/common/cpp/audioapi/HostObjects/sources/AudioBufferSourceNodeHostObject.h
packages/react-native-audio-api/common/cpp/audioapi/core/effects/WorkletNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferBaseSourceNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioBufferSourceNode.h
packages/react-native-audio-api/common/cpp/audioapi/core/sources/AudioScheduledSourceNode.cpp
packages/react-native-audio-api/common/cpp/audioapi/events/AudioEventHandlerRegistry.h
packages/react-native-audio-api/src/core/AudioBufferBaseSourceNode.ts
packages/react-native-audio-api/src/core/AudioBufferQueueSourceNode.ts
packages/react-native-audio-api/src/core/AudioBufferSourceNode.ts
packages/react-native-audio-api/src/events/types.ts
packages/react-native-audio-api/src/interfaces.ts

Closes RNAA-226
-
- Added `onLoopEnded` event to `AudioBufferSourceNode`

feat: added onLoopEnded callback
